spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:todolist;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  application:
    name=todo

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  jpa:
    defer-datasource-initialization: true

  session:
    timeout: 86400


server:
  servlet:
    encoding:
      force-response: true
    session:
      cookie:
        max-age: 172800

todo:
  jwt-key: "cg4OvepxZJrbMzO0i2rPDEKpr0CCsuuIQV8w8plXhbk="