spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:todolist
    username: sa
    password:
    driver-class-name: org.h2.Driver
  application:
    name=todo


server:
  servlet:
    encoding:
      force-response: true
