spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:todolist;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  application:
    name=todo

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  jpa:
    defer-datasource-initialization: true

sql:
  init:
    mode: always

server:
  servlet:
    encoding:
      force-response: true

todo:
  hello:
    hobby: "dd"
    age: 23