spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:todolist
    username: sa
    password:
    driver-class-name: org.h2.Driver
  application:
    name=todo

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5


server:
  servlet:
    encoding:
      force-response: true
